# Generated by Django 6.0.2 on 2026-03-24 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_instructorprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
