# Generated by Django 6.0.2 on 2026-03-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_content_order_module_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.FloatField(default=0.0, help_text='Duration in hours'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='raiting',
            field=models.FloatField(default=0.0),
        ),
    ]
