# Generated by Django 6.0.2 on 2026-03-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_duration_course_image_course_level_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="raiting",
            new_name="rating",
        ),
    ]
